language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: OnB9yKbuOIlE2m/yjTKhJtKsklYKAlZuzIOGjZt5KtaiNVjO/0TPjCzFfYHya6GL/GKD3abvMXW/Gpw8w29bcGtc6cE9LdYq4bDAxTOxI2MvVv9KDZ0I7FGZux1yRLL5KPs3AHR+yzBTHSrfpoa8GcRv5/qXHJgiBvFGoG4ZOMeUEEwXIDsRpIZWd3vHFjoh2Drb1Gegux6gIFy6q8oJ67Sz4fVgo2cM0eLiLm8ZisRuyZfJyOOIRJZp6GpyOFqQpRv3JiJRluqAQjQzAE97C83rChwmlDqRWnwwk3GQhAoyiuP0Rd3fIgUzQaeqp0y/LA2XWEFm7sfAtznuELYbEIa/Isj96KLj2UwN0of9kx3G92Uf4j71HMnLDca9vC8t/E1jdcpGCdE28FTtvIlF3gLTpnkxlylBVPwr7ExNaAUjuhPUQGtrKDZl0JDbP8e/fcF74qwy8fvpZ5UJ/IFGwXAbXjShrwUrXgjz31w9QzTpa9gIdnlwuq1/3DcSAkE5/nr06lRz32QkacroDLx6J7rCz/hLsmjff9FVIc6FlYwnF7Gi2CHmMqwGNr/AL/lq1OL6bNcWv0wJe1uhWlDASdK2iW2tG9j2JTLostDlmNKomXR25vs47R0rjOPqS/MChevWV4Rh8I5hEhJipJFEYwzJ0eQePvhjhEyaYNXAfVk=
  - secure: S613gnt595QI+4yXJeDrU1/blo4gCAHp79YcpYSGvg5/y4jOXQlfghVFvFHq+ktl7jEyYqOarGBxB5eJ/shoQeYSqtFcdhaKXkirEtkfrxKYDB2qkfGGc9kdjdrOUEWlj+yfEZNsSqNBCxtDrh4rJyZcD/OXMidgg3nF87fC3pmVIj2C8VeWGCQVIBMPmvsrk1NDPi+SxwFQEQYhZXYUmWB6rtOCBKtjeqZCYS5xApO5trRDRL9qqYBweErCKeRh6GcFxhCA13FLTRw+3AhQWkBQeKZ2DbHyipKDXCyWb84+Q5ElOjF7DjxU4gU7QuO2DyfSCKma30+4c+bwIKamhyiku6zy7eQMYw9cJpLSDFFJ+1Dvu7IBSi3l7+lfXIM8YuFxSitQtnqfAUnbTcIeBQe0+rqI6Xp6tl03sRiEav3kMz8LT1215ztRKW6QrX5Yk1hG9CSSBH+ku66sDeMsWM7oIpo2Mx9KkOuHi+972iqcxMQ/wcZAo1wC2Ks7HaZBbPcp6MLHn9IG2WyfQXd9W/duYWwZ4tBGGIatRic6f90+luRR7uhcDlxFeN9vde1I7uEOhzgRR6ZTla2gUWh7FhITC/lF637fJXr5l4ls+8lGDOfbgPuo4FmsMEUyrN70GHgfhcPdPZH5hahGqXp4W77M0nRXWo5CzG7qZRmcCic=
